#!/usr/bin/env zsh

YABAI_CONFIG="$HOME/.config/yabai"

# This is used to determine if a monitor is used
# Since the notch is -only- on the laptop, if a monitor isn't used,
# then that means the internal display is used ¯\_(ツ)_/¯
MAIN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:' | awk '/Display Type/ {print $3}')

if [[ $MAIN_DISPLAY = "Built-in" ]]; then
   source "$YABAI_CONFIG/yabai-laptop"
else
   source "$YABAI_CONFIG/yabai-desktop"
fi
